export const routes = {
  home: '/',
  login: '/login',
  signup: '/signup',
  projects: '/projects',
  newProject: '/projects/new',
  request: '/requests',
  requestQuestions: '/requests/questions',
  requestStructured: '/requests/structured',
  formulas: '/formulas',
  formulaDetail: (id: string | number) => `/formulas/${id}`,
  formulaManagement: '/formula-management',
  experiments: '/experiments',
  ingredients: '/ingredients',
  organization: '/organization',
  organizationMembers: '/organization/members',
  operations: '/operations',
  profile: '/profile',
} as const;
